apiVersion: v1
kind: Service
metadata:
  name: {{ include "cloud-pricing-api.fullname" . }}
  annotations:
{{ toYaml .Values.service.annotations | indent 4 }}
  labels:
    {{- include "cloud-pricing-api.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "cloud-pricing-api.selectorLabels" . | nindent 4 }}
